blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
comment_width = 80
error_on_line_overflow = true
fn_params_layout = "Compressed"
force_multiline_blocks = true
hard_tabs = true
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
struct_lit_single_line = false
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
