brace_style = "AlwaysNextLine"
hard_tabs = true
wrap_comments = true
comment_width = 100
max_width = 100
fn_call_width = 100
fn_params_layout = "Compressed"
force_multiline_blocks = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
